class User {
  static FETCH_DETAILS_START = "USER_FETCH_DETAILS_START";
  static FETCH_DETAILS_SUCESS = "USER_FETCH_DETAILS_SUCESS";
  static FETCH_DETAILS_FAILURE = "USER_FETCH_DETAILS_FAILURE";
  static LOG_OUT = "USER_LOG_OUT";
  static CLEAR_DETAILS = "USER_CLEAR_DETAILS";
}

export default User;
