const UserActionTypes = {
  LOG_IN_START: "USER_LOG_IN_START" as "USER_LOG_IN_START",
  LOGIN_IN_SUCCESS: "USER_LOGIN_IN_SUCCESS" as "USER_LOGIN_IN_SUCCESS",
  LOGIN_IN_FAILURE: "USER_LOGIN_IN_FAILURE" as "USER_LOGIN_IN_FAILURE",
  LOG_OUT: "USER_LOG_OUT" as "USER_LOG_OUT",
  CLEAR_DETAILS: "USER_CLEAR_DETAILS" as "USER_CLEAR_DETAILS",
  CHANGE_SETTING_START: "USER_CHANGE_SETTING_START" as "USER_CHANGE_SETTING_START",
  CHANGE_SETTING_SUCCESS: "USER_CHANGE_SETTING_SUCCESS" as "USER_CHANGE_SETTING_SUCCESS",
};

export default UserActionTypes;
