const AlertActionTypes = {
  FETCH_ALERTS_START: "ALERTS_FETCH_ALERTS_START" as "ALERTS_FETCH_ALERTS_START",
  FETCH_ALERTS_SUCCESS: "ALERTS_FETCH_ALERTS_SUCCESS" as "ALERTS_FETCH_ALERTS_SUCCESS",
  FETCH_ALERTS_FAILURE: "ALERTS_FETCH_ALERTS_FAILURE" as "ALERTS_FETCH_ALERTS_FAILURE",
  SET_ALERT_START: "ALERTS_SET_ALERT_START" as "ALERTS_SET_ALERT_START",
};

export default AlertActionTypes;
