class CurrenciesActionTypes {
  static FETCH_CURRENCIES_START = "CURRENCIES_FETCH_CURRENCIES_START";
  static FETCH_CURRENCIES_SUCCESS = "CURRENCIES_FETCH_CURRENCIES_SUCCESS";
  static FETCH_CURRENCIES_FAILURE = "CURRENCIES_FETCH_CURRENCIES_FAILURE";
}

export default CurrenciesActionTypes;
