const CurrenciesActionTypes = {
  FETCH_CURRENCIES_START: "CURRENCIES_FETCH_CURRENCIES_START" as "CURRENCIES_FETCH_CURRENCIES_START",
  FETCH_CURRENCIES_SUCCESS: "CURRENCIES_FETCH_CURRENCIES_SUCCESS" as "CURRENCIES_FETCH_CURRENCIES_SUCCESS",
  FETCH_CURRENCIES_FAILURE: "CURRENCIES_FETCH_CURRENCIES_FAILURE" as "CURRENCIES_FETCH_CURRENCIES_FAILURE",
};

export default CurrenciesActionTypes;
