import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className="bg-neutral-200 h-screen font-sans text-neutral-900/70">
      <div className="relative mx-auto flex flex-col bg-clip-padding bg-opacity-10 backdrop-filter bakdrop-blur-lg h-full">
        <Head>
          <title>Erate</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </div>
    </div>
  );
}

export default MyApp;
